#!/usr/bin/env bash
#
# Prints docs/exclusions.md from the lists in bin/ziproj, so the documentation
# cannot drift from the code. `make docs` writes it; `make lint` checks it.

set -o pipefail

HERE=$(cd "$(dirname "$0")" && pwd -P)
SRC="$HERE/../bin/ziproj"

# Load only the array definitions, never the rest of the script.
for name in SECRET_FILES JUNK_FILES SECRET_DIRS JUNK_DIRS AI_EXTENSIONS; do
    block=$(awk -v n="$name" '$0 ~ ("^" n "=\\(") { p = 1 } p { print } p && /\)[[:space:]]*$/ { exit }' "$SRC")
    [ -n "$block" ] || { echo "cannot find $name in $SRC" >&2; exit 1; }
    eval "$block"
done

list() { # list ITEM... -> `a`, `b`, `c`
    local out="" item
    for item in "$@"; do
        out="$out${out:+, }\`$item\`"
    done
    printf '%s\n' "$out"
}

cat <<'EOF'
# Default exclusions

<!-- Generated by scripts/gen-exclusions-doc.sh from bin/ziproj. Do not edit by hand: run `make docs`. -->

These rules always apply, whether a file is tracked by git or not, at any depth in the project.
`*` matches any characters, including `/`. Add your own rules with `-x` or an
[ignore file](configuration.md#ignore-files).

## Files that hold secrets

Matched in any letter case: `.ENV` and `Server.PEM` are excluded too, since the default macOS file system treats them as the same names.

EOF
list "${SECRET_FILES[@]}"
cat <<'EOF'

## Folders that hold secrets

Excluded with everything inside them, in any letter case.

EOF
list "${SECRET_DIRS[@]}"
cat <<'EOF'

## Dead weight: files

OS litter, logs, compiled objects, app packages and archives.

EOF
list "${JUNK_FILES[@]}"
cat <<'EOF'

## Dead weight: folders

Version control data, dependencies, build output and caches, excluded with everything inside them. These names are case-sensitive, so a source folder called `Build` is kept.

EOF
list "${JUNK_DIRS[@]}"
cat <<'EOF'

## AI mode (`-a`)

These extensions are also excluded with `-a`, in any letter case (`.PNG` as well as `.png`).

EOF
list "${AI_EXTENSIONS[@]}"
